# Generated by Django 3.2.8 on 2024-04-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_request_attachment',
            field=models.FileField(blank=True, null=True, upload_to='service_requests/'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_request_type',
            field=models.CharField(choices=[('gas_cylinder', 'Gas Cylinder'), ('other_equipment', 'Other Equipment')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
